<a href="https://colab.research.google.com/github/Twilight1029/Python-for-Data-Analysis/blob/main/Python_for_Data_Analysis_CH5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CHAPTER 5 Getting Started with Pandas

Pandas is designed for working with tabular or heterogeneous data.

### 5.1 Introduction to pandas Data Structures

In [ ]:
import pandas as pd
from pandas import Series, DataFrame

1. Series<br>
A Series is a one-dimensional array-like object containing a sequence of values (of similar types to NumPy types) and an associated array of data labels, called its index.

In [ ]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [ ]:
obj.index # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [ ]:
obj2['a']

-5

In [ ]:
obj2['d'] = 6

In [ ]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [ ]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [ ]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [ ]:
import numpy as np

In [ ]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [ ]:
# Series is as a fixed-length, ordered dict
# as it is a mapping of index values to data values.

'b' in obj2

True

In [ ]:
'e' in obj2

False

In [ ]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon': 16000, 'Utah' : 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
# you can pass the dict keys in the order yo want
# NaN(not a number) --> to mark missing or NA values

states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [ ]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [ ]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [ ]:
# A Series’s index can be altered in-place by assignment:

obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

2. DataFrame<br>
A DataFrame represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type

In [ ]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
        'year':[2000, 2001, 2002, 2001, 2002, 2003],
       'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [ ]:
# columns can be arranged in responding order

pd.DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [ ]:
# If you pass a column that isn’t contained in the dict, 
# it will appear with missing values in the result

frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [ ]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
# can be retrieved as a Series either by dict-like notation or by attribute

frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [ ]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [ ]:
# NOTE: frame2[column] works for any column name, but frame2.column 
# only works when the column name is a valid Python variable name.

In [ ]:
# Rows can also be retrieved by position or name with the special loc attribute

frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [ ]:
# Columns can be modified by assignment.

frame2['debt'] = 16.5

In [ ]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [ ]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [ ]:
# If you assign a Series, its labels will be realigned exactly to 
# the DataFrame’s index, inserting missing values in any holes:

val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [ ]:
# Assigning a column that doesn’t exist will create a new column.
# The del keyword will delete columns as with a dict

frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [ ]:
# del method can be used to remove this column

del frame2['eastern']

frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
# Another common form of data is a nested dict of dicts

pop = {'Nevada':{2001:2.4, 2002:2.9},
      'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}

In [ ]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [ ]:
# You can transpose the DataFrame (swap rows and columns)

frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [ ]:
# can change the index by reassigning value to it

pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [ ]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [ ]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}

pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [ ]:
# If a DataFrame’s index and columns have their name attributes set,
# these will also be displayed

frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [ ]:
# values attribute returns the data contained in the DataFrame 
# as a two-dimensional ndarray

frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [ ]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

![image.png](attachment:image.png)

3. Index Objects<br>
pandas’s Index objects are responsible for holding the axis labels and other metadata(like the axis name or names). <br>
Any array or other sequence of labels you use when constructing a Series or DataFrame is internally converted to an Index:

In [ ]:
obj = pd.Series(range(3), index = ['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
index[1:]

Index(['b', 'c'], dtype='object')

In [ ]:
index[1]

'b'

In [ ]:
# Immutability makes it safer to share Index objects among data structures

labels = pd.Index(np.arange(3))

labels

Int64Index([0, 1, 2], dtype='int64')

In [ ]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [ ]:
obj2.index is labels

True

In [ ]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [ ]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [ ]:
'Ohio' in frame3.columns

True

In [ ]:
2003 in frame3.index

False

In [ ]:
# a pandas Index can contain duplicate labels
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

![image.png](attachment:image.png)

### 5.2 Essential Functionality
The fundamental mechanics of interacting with the data contained in a Series or DataFrame

1. Reindexing<br>
To create a new object with the data conformed to a new index

In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [ ]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [ ]:
# ffill, which forward-fills the values

obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [ ]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [ ]:
# With DataFrame, reindex can alter either the (row) index, columns, or both. 
# When passed only a sequence, it reindexes the rows in the result

frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index = ['a', 'c', 'd'],
                     columns = ['Ohio', 'Texas', 'California'])

frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [ ]:
# The columns can be reindexed with the columns keyword

states = ['Texas', 'Utah', 'California']
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

![image.png](attachment:image.png)

2. Dropping Entries from an Axis<br>
Drop method will return a new object with the indicated value or values deleted from an axis

In [ ]:
obj = pd.Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [ ]:
# With DataFrame, index values can be deleted from either axis

data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index = ['Ohio', 'Colorado', 'Utah', 'New York'],
columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [ ]:
data.drop(['two', 'four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [ ]:
# Inplace, it destroys any data that is dropped
obj.drop('c', inplace = True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

3. Indexing, Selection, and Filtering <br>
Series indexing (obj[...]) works analogously to NumPy array indexing, except you can use the Series’s index values instead of only integers.

In [ ]:
obj = pd.Series(np.arange(4.), index = ['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [ ]:
obj['b']

1.0

In [ ]:
obj[1]

1.0

In [ ]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [ ]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [ ]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [ ]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [ ]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [ ]:
# Setting using these methods modifies the corresponding section of the Series

obj['b': 'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [ ]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                   index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [ ]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [ ]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [ ]:
# slicing or selecting data with a boolean array

data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [ ]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

4. Selection with loc and iloc <br>
They enable you to select a subset of the rows and columns from a DataFrame with NumPy-like notation using either axis labels (loc) or integers
(iloc).

In [ ]:
# select a single row and multiple columns by label

data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [ ]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [ ]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [ ]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [ ]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
# Both indexing functions work with slices in addition to single labels or lists of labels

data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [ ]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

![image.png](attachment:image.png)
![image-2.png](attachment:image-2.png)

4. Integer Indexes

In [ ]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [ ]:
ser2 = pd.Series(np.arange(3.), index = ['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [ ]:
ser2[-1]

2.0

In [ ]:
# if you have an axis index containing integers, data selection
# will always be label-oriented. For more precise handling, 
# use loc (for labels) or iloc (for integers)

ser[:1]

0    0.0
dtype: float64

In [ ]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [ ]:
ser.iloc[:1]

0    0.0
dtype: float64

In [ ]:
ser2[:1]

a    0.0
dtype: float64

In [ ]:
ser2[:-1]

a    0.0
b    1.0
dtype: float64

In [ ]:
ser2.iloc[:1]

a    0.0
dtype: float64

In [ ]:
# cannot use ser2.loc[:1], will get an error
ser2.loc['a']

0.0

5. Arithmetic and Data Alignment<br>
This is similar to an automatic outer join on the index labels

In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
              index = ['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [ ]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [ ]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [ ]:
# In the case of DataFrame, 
# alignment is performed on both the rows and the columns

df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns = list('bcd'),
                   index = ['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns = list('bde'),
                   index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [ ]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [ ]:
# If you add DataFrame objects with no column or row labels in common,
# the result will contain all nulls

df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [ ]:
df1

A
0  1
1  2

In [ ]:
df2

B
0  3
1  4

In [ ]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

6. Arithmetic methods with fill values<br>
In arithmetic operations between differently indexed objects, you might want to fill with a special value, like 0, when an axis label is found in one object but not the other

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns = list('abcde'))

In [ ]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df2.loc[1, 'b'] = np.nan

In [ ]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
# add on df1, pass df2 and an argument to fill_value

df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
# use x.rdiv(n) == n/x

1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
df1.reindex(columns = df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

![image.png](attachment:image.png)

7. Operations between DataFrame and Series<br>
As with NumPy arrays of different dimensions, arithmetic between DataFrame and
Series is also defined.

In [ ]:
arr = np.arange(12.).reshape((3, 4))

In [ ]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
arr[0]

array([0., 1., 2., 3.])

In [ ]:
# When we subtract arr[0] from arr, the subtraction is performed once for each row.
# This is referred to as broadcasting

arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [ ]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns = list('bde'),
                    index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [ ]:
series = frame.iloc[0]

In [ ]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [ ]:
# loc can accept integers and also column name as index
frame.loc[:,'b']

Utah      0.0
Ohio      3.0
Texas     6.0
Oregon    9.0
Name: b, dtype: float64

In [ ]:
# iloc can only accept integers as index
frame.iloc[:, 0]

Utah      0.0
Ohio      3.0
Texas     6.0
Oregon    9.0
Name: b, dtype: float64

In [ ]:
frame - series

b   d     e   f
Utah    0.0 NaN   1.0 NaN
Ohio    3.0 NaN   4.0 NaN
Texas   6.0 NaN   7.0 NaN
Oregon  9.0 NaN  10.0 NaN

In [ ]:
series = pd.Series(range(3), index = ['b', 'e', 'f'])

In [ ]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
series

b    0
e    1
f    2
dtype: int64

In [ ]:
# If an index value is not found in either the DataFrame’s columns 
# or the Series’s index, the objects will be reindexed to form the union:
frame + series

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [ ]:
# If you want to instead broadcast over the columns, matching on the rows, 
# you have to use one of the arithmetic methods.

series3 = frame['d']

frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [ ]:
# The axis number that you pass is the axis to match on. 
# In this case we mean to match on the DataFrame’s row index (axis='index' or axis=0) 
# and broadcast across

frame.sub(series3, axis = 'index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

8. Function Application and Mapping<br>
NumPy ufuncs (element-wise array methods) also work with pandas objects

In [ ]:
frame = pd.DataFrame(np.random.randn(4, 3),
                    columns = list('bde'),
                    index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    1.987569  0.500237  0.015882
Ohio   -0.721061 -1.156149  0.744722
Texas  -1.011431  1.730750  0.310174
Oregon  1.021279 -0.408382 -0.866135

In [ ]:
np.abs(frame)

b         d         e
Utah    1.987569  0.500237  0.015882
Ohio    0.721061  1.156149  0.744722
Texas   1.011431  1.730750  0.310174
Oregon  1.021279  0.408382  0.866135

In [ ]:
# apply --> applying a function on one-dimensional arrays to each column or row
# by default, columns
# change axis = 'columns', per row

f = lambda x : x.max() - x.min()

frame.apply(f)

b    2.999000
d    2.886900
e    1.610857
dtype: float64

In [ ]:
frame.apply(f, axis = 'columns')

Utah      1.971687
Ohio      1.900871
Texas     2.742181
Oregon    1.887414
dtype: float64

In [ ]:
frame.apply(f, axis = 1)

Utah      1.971687
Ohio      1.900871
Texas     2.742181
Oregon    1.887414
dtype: float64

In [ ]:
# The function passed to apply need not return a scalar value; 
# it can also return a Series with multiple values:

def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])

In [ ]:
frame.apply(f)

b         d         e
min -1.011431 -1.156149 -0.866135
max  1.987569  1.730750  0.744722

In [ ]:
# you wanted to compute a formatted string from each floating-point value in frame. 
# You can do this with apply map

format = lambda x: '%.2f' % x

In [ ]:
frame.applymap(format)

b      d      e
Utah     1.99   0.50   0.02
Ohio    -0.72  -1.16   0.74
Texas   -1.01   1.73   0.31
Oregon   1.02  -0.41  -0.87

In [ ]:
# series has a map method for applying an element-wise function

frame['e'].map(format)

Utah       0.02
Ohio       0.74
Texas      0.31
Oregon    -0.87
Name: e, dtype: object

9. Sorting and Ranking<br>
To sort lexicographically by row or column index, use the sort_index method, which returns a new, sorted object

In [ ]:
obj = pd.Series(range(4), index = ['d', 'a', 'b', 'c'])

In [ ]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [ ]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index = ['three', 'one'],
                    columns = ['d', 'a', 'b', 'c'])

In [ ]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [ ]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [ ]:
# The data is sorted in ascending order by default

frame.sort_index(axis = 1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [ ]:
# To sort a Series by its values, use its sort_values method

obj = pd.Series([4, 7, -3, 2])

In [ ]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [ ]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [ ]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [ ]:
frame = pd.DataFrame({'b' : [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [ ]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [ ]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [ ]:
frame.sort_values(by = ['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [ ]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [ ]:
# rank the index, if the two values are equal, we get n+m/2

obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [ ]:
# first come, first rank 

obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [ ]:
# Assign tie values the maximum rank in the group

obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [ ]:
# DataFrame can compute ranks over the rows or the columns

frame = pd.DataFrame({'b':[4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                     'c':[-2, 5, 8, -2.5]})

In [ ]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [ ]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

![image.png](attachment:image.png)

10. Axis indexes with Duplicate Labels<br>
Many pandas functions (like reindex) require that the labels be unique

In [ ]:
obj = pd.Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])

In [ ]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [ ]:
# The index’s is_unique property can tell you whether its labels are unique or not

obj.index.is_unique

False

In [ ]:
#  Indexing a label with multiple entries returns a Series, 
# while single entries return a scalar value:

obj['a']

a    0
a    1
dtype: int64

In [ ]:
obj['c']

4

In [ ]:
df = pd.DataFrame(np.random.randn(4, 3), index = ['a', 'a', 'b', 'b'])
df

0         1         2
a  0.726628 -0.150414 -0.640998
a  1.320778  0.184470  1.725548
b -1.109659  0.689485 -0.105723
b -0.962359  0.984817  0.538085

In [ ]:
df.loc['b']

0         1         2
b -1.109659  0.689485 -0.105723
b -0.962359  0.984817  0.538085

### 5.3 Summarizing and Computing Descriptive Statistics
Pandas objects are equipped with a set of common mathematical and statistical methods -------->reductions or summary statistics, methods.<br>
That extract a single value (like the sum or mean) from a Series or a Series of values from the rows or columns of a DataFrame.

In [ ]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                 [np.nan, np.nan], [0.75, -1.3]],
                 index=['a', 'b', 'c', 'd'],
                 columns = ['one', 'two'])

In [ ]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [ ]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [ ]:
df.sum(axis = 'columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [ ]:
# NA values are excluded unless the entire slice (row or column in this case) is NA.

df.mean(axis = 'columns', skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

![image.png](attachment:image.png)

In [ ]:
# Some methods, like idxmin and idxmax, return indirect statistics 
# like the index value where the minimum or maximum values are attained:

df.idxmax()

one    b
two    d
dtype: object

In [ ]:
df.idxmin()

one    d
two    b
dtype: object

In [ ]:
# accumulations
# by default, cumsum by columns

df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [ ]:
# describe produces multiple summary statistics in one shot

df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [ ]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [ ]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

* a full list of summary statistics and related methods
![image.png](attachment:image.png)

1. Correlation and Covariance<BR>
DataFrames of stock prices and volumes obtained from Yahoo! Finance using the add-on **pandas-datareader package**

In [ ]:
!pip install pandas-datareader

In [ ]:
import pandas_datareader.data as web

In [ ]:
all_data = {ticker : web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [ ]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [ ]:
returns = price.pct_change()

In [ ]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2020-11-18 -0.011391 -0.007901 -0.013184 -0.013202
2020-11-19  0.005168  0.003511  0.006348  0.009812
2020-11-20 -0.010958 -0.002048 -0.009557 -0.012319
2020-11-23 -0.029743  0.026937 -0.001331 -0.004207
2020-11-24  0.011594  0.036056  0.017848  0.019610

In [ ]:
# The corr method of Series computes the correlation of the overlapping, 
# non-NA, aligned-by-index values in two Series. 
# Relatedly, cov computes the covariance

returns['MSFT'].corr(returns['IBM'])

0.5611814207623687

In [ ]:
returns['MSFT'].cov(returns['IBM'])

0.0001602763927889609

In [ ]:
returns.MSFT.corr(returns.IBM)

0.5611814207623687

In [ ]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.476077  0.718580  0.657193
IBM   0.476077  1.000000  0.561181  0.522143
MSFT  0.718580  0.561181  1.000000  0.780960
GOOG  0.657193  0.522143  0.780960  1.000000

In [ ]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000361  0.000147  0.000239  0.000208
IBM   0.000147  0.000265  0.000160  0.000142
MSFT  0.000239  0.000160  0.000308  0.000228
GOOG  0.000208  0.000142  0.000228  0.000278

In [ ]:
# use corrwith method, you can compute pairwise correlations
# between a DataFrame’s columns or rows with another Series or DataFrame

# BELOW we get the corr between other companies and IBM
returns.corrwith(returns.IBM)

AAPL    0.476077
IBM     1.000000
MSFT    0.561181
GOOG    0.522143
dtype: float64

In [ ]:
returns.corrwith(volume)

AAPL   -0.096608
IBM    -0.075711
MSFT   -0.096670
GOOG   -0.164053
dtype: float64

In [ ]:
# row-by-row
returns.corrwith(volume, axis = 'columns')

Date
2015-11-27         NaN
2015-11-30    0.342488
2015-12-01   -0.885483
2015-12-02   -0.038582
2015-12-03    0.112309
                ...   
2020-11-18   -0.130221
2020-11-19   -0.289891
2020-11-20   -0.348502
2020-11-23   -0.814607
2020-11-24   -0.684439
Length: 1258, dtype: float64

2. Unique Values, Value Counts, and Membership<Br>
Extracts information about the values contained in a one-dimensional Series.

In [ ]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [ ]:
uniques = obj.unique()

In [ ]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [ ]:
# sort the returned value --> uniques.sort()
# value_counts computes a Series containing value frequencies (descending order)

obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [ ]:
pd.value_counts(obj.values, sort=False)

b    2
c    3
a    3
d    1
dtype: int64

In [ ]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [ ]:
# use isin as a filter
mask = obj.isin(['b', 'c'])

In [ ]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [ ]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [ ]:
# Index.get_indexer method, which gives you an index array
# from an array of possibly non-distinct values into 
# another array of distinct values

to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])

In [ ]:
# give you the corresponding index in another array

pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

![image.png](attachment:image.png)

In [ ]:
# get a histogram

data = pd.DataFrame({'Qu1':[1, 6, 4, 3, 4],
                     'Qu2':[2, 3, 1, 2, 3],
                     'Qu3':[1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    6    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [ ]:
result = data.apply(pd.value_counts).fillna(0)

In [ ]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  1.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0
6  1.0  0.0  0.0

In [ ]:
data.apply(pd.value_counts)

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  1.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0
6  1.0  NaN  NaN

In [ ]:
pd.value_counts

<function pandas.core.algorithms.value_counts(values, sort: bool = True, ascending: bool = False, normalize: bool = False, bins=None, dropna: bool = True) -> 'Series'>